Fix building with tcc on FreeBSD (re: 40c70507, 22e044c3)
As of the first referenced commit, building with tcc on FreeBSD
fails as follows: [...]/src/cmd/ksh93/sh/arith.c:42: error:
initializer element is not constant

POSIX requires that NAN and INFINITY are constant expressions, but
in practice, this is apparently not guaranteed.

src/cmd/ksh93/sh/arith.c:
- Go back to assigning Inf and NaN at runtime on first use. Since
  these no longer require a strtold call, the cost is negligible.