[v1.0] reseed $RANDOM: use fmod(3), not remainder(3) (re: af6a32d1)
@puddles123fluffy reports:
> Building ksh93 from pkgsrc on NetBSD/vax fails during the final
> compilation/linking of the ksh93 binary with this message:
>
> # src/cmd/ksh93/Mamfile: 1096-1103: make ksh
> + link_binary ksh pmain.o
[...]
> ld: libshell.a(init.o): in function `sh_reseed_rand':
> init.c:(.text+0x1c4c): undefined reference to `remainder'

Turns out remainder(3) is not present in NetBSD libm on the vax,
though the headers define it and the man page documents it.

However... I reconsidered the function, and it looks like my use of
remainder(3) from commit af6a32d1 was WRONG anyway, because
remainder may return negative values for two positive inputs, and
casting a negative floating-point value to an unsigned int is
undefined behaviour. What I really wanted was fmod(3), the floating
point remainder function.

Greg A. Woods (@robohack) comments:
> Fundamentally of course this problem is rooted in the fact that
> VAX hardware does not use IEEE-754 floating point (it uses its
> own format)[1], and GCC for VAX does't support -msoft-float
> either. libm on NetBSD/vax, or pretty much any Unix on VAX, is
> its own beast.
>
> There is an fmod(3) implementation in NetBSD's
> src/lib/libm/noieee_src/n_fmod.c so using it instead of
> remainder() should work on NetBSD/vax.
>
> [1] http://www.eecs.berkeley.edu/~wkahan/ieee754status/754story.html

So, both this build failure and the potential UB are fixed by using
fmod(3) instead.

Resolves: https://github.com/ksh93/ksh/issues/977