Fix compiling with strict C99 and C11
This commit fixes compilation of ksh with strict C99 and strict C11.
It has been tested on the following operating systems (amd64):
- Arch Linux (w/ glibc 2.37)
- Void Linux (w/ musl libc 1.1.24)
- FreeBSD 13.2
- DragonFly BSD 6.4
- NetBSD 9.3
- OpenBSD 7.3
- OmniOS CE r151046
- Haiku R1/beta4

Additionally, -std=c11 has been fixed on Cygwin, but due to some sort of
bug or incompatibility in the Win32 API -std=c99 doesn't compile:
+ cc -D_BLD_ast -Os -I. -I/home/ksh/src/lib/libast -Icomp -I/home/ksh/src/lib/libast/comp -Iinclude -I/home/ksh/src/lib/libast/include -Istd -I/home/ksh/src/lib/libast/std -c /home/ksh/src/lib/libast/path/pathprog.c
/usr/include/w32api/libloaderapi.h:148:14: error: expected ')' before '__attribute__'
  148 |   WINBASEAPI DECLSPEC_NORETURN VOID WINAPI FreeLibraryAndExitThread (HMODULE hLibModule, DWORD dwExitCode);
      |              ^~~~~~~~~~~~~~~~~
/usr/include/w32api/libloaderapi.h:148:14: error: expected identifier or '(' before ')' token
  148 |   WINBASEAPI DECLSPEC_NORETURN VOID WINAPI FreeLibraryAndExitThread (HMODULE hLibModule, DWORD dwExitCode);
... etc.
I'm not inclined to work around this because -std=c11 does work,
and also because it takes ages to compile anything on Cygwin.

The following operating systems have not been tested yet, as I
currently don't have access to any of them:
- macOS
- Oracle Solaris
- QNX
- HP/UX
- AIX
- UnixWare

For testing, I used a cc wrapper that passes all the required compiler
flags. Example script:
  #!/bin/sh
  # Note: Don't extend the argument list to multiple lines with \
  exec cc -std=c99 -Werror=implicit-function-declaration -Werror=implicit-int -Werror=int-conversion -Werror=old-style-definition "$@"
The compilers tested consist of many versions of gcc, ranging from
GCC 8 up to the current 14.0 git commit. In a similar vein, Clang
has been tested on versions ranging from 13.0.0 to the current
17.0 git commit; tcc's latest git commit was also tested.

Changes:
- Removed all old style function definitions and updated them for
  compatibility with C99 and C23. This is primarily done by changing
  e.g. 'int main()' to 'int main(void)'. There were also a few obsolete
  K&R C constructs that needed modernization.

- Fixed the avalanche of -Wbuiltin-macro-redefined warnings in LLVM
  17. Clang 17 (git version) was spamming the terminal with an
  avalanche of -Wbuiltin-macro-redefined warnings during the build.
  This was caused by pre-existing hackery that force defined -Os
  in the C code itself. This is unnecessary and thus the best way
  to fix the warning avalanche is to remove the macro hackery.

- Fixed mamake compile when using -std=c*. The mamake compile broke
  because POSIX functionality was disabled by the compiler flag.
  Code from src/lib/libast/features/standards for enabling
  feature macros has been reused here to fix the build with -std=c99.

- The build failed in tvsleep.c because of borked header includes.
  Fixed easily enough by adding an include for ast.h (and updating
  the requisite mamfile).

- Removed incorrect usage of _ATFILE_SOURCE. When compiling on Linux
  with Clang 17, iffe failed to detect the utimensat function
  correctly. This was caused by blatantly incorrect usage of
  _ATFILE_SOURCE. If this actually needed to be defined, the correct
  location for it is in src/lib/libast/features/standards. However,
  the current macros enable this by default on illumos and glibc 2.10+
  via __EXTENSIONS__ and _GNU_SOURCE respectively, making it at best
  redundant to manually define it, or (in this case) harmful.

- Fixed -std=c99 on NetBSD by avoiding the getfsstat function. The
  getfsstat function is only provided on NetBSD for binary
  compatibility and nothing else. As a result, it is not exposed in
  the headers and using it will cause an implicit function error,
  killing the build with C99. Iffe detects this function because it
  does exist on NetBSD, and the comments in mnt.c imply this is
  intentional. Despite that, using the function on NetBSD via an
  implicit call is impossible in C99, the function is deprecated,
  and we don't actually need to use it, so it's best to just avoid
  getfsstat by undefining the iffe macro for it.

- Fix compiling with -std=c99 on Haiku. On Haiku, the math.h header
  doesn't have an extern or definition for isnanl, which causes the
  build to fail with C99. The fpclassify function works just
  fine, so that's a better choice here than isnanl.

- Removed an unused program from src/lib/libast/misc/recfmt.c that
  suffered from bitrot.

- Since quite a few operating systems were tested as of this commit,
  the list of tested operating systems in src/cmd/ksh93/README has
  been updated to reflect this.

Resolves: https://github.com/ksh93/ksh/issues/587